#!/usr/bin/env bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


# Determines all branches that should be synced in the current session.
# Stores its result in the global variable "$branches_to_sync".
function determine_branches_to_sync {
  if [ "$sync_target" = "all branches" ]; then
    IFS=$'\n'
    branches_to_sync=($(local_branches_with_main_first))
  elif [ "$sync_target" = "feature branch" ]; then
    IFS=$'\n'
    branches_to_sync=($(ancestor_branches "$INITIAL_BRANCH_NAME" | tr ' ' '\n'))
    branches_to_sync+=$INITIAL_BRANCH_NAME
  elif [ "$sync_target" = "perennial branch" ]; then
    branches_to_sync=($INITIAL_BRANCH_NAME)
  else
    echo_error_header "Unknown sync target"
    exit_with_error
  fi
}


function preconditions {
  if [ "$HAS_REMOTE" = true ]; then
    fetch
  fi

  should_push_tags=false
  sync_target=""

  if [ "$1" = "--all" ]; then
    sync_target="all branches"
    should_push_tags=true
    local branches="$(local_branches_without_main | tr '\n' ' ')"
    ensure_knows_parent_branches "$branches"
  elif [ "$(is_feature_branch "$INITIAL_BRANCH_NAME")" = true ]; then
    sync_target="feature branch"
    ensure_knows_parent_branches "$INITIAL_BRANCH_NAME"
  else
    sync_target="perennial branch"
    should_push_tags=true
  fi

  export RUN_IN_GIT_ROOT=true
  export STASH_OPEN_CHANGES=true
}


function skip_message_prefix {
  echo "To skip the sync of the '$(get_current_branch_name)' branch"
}


function skippable {
  if [ "$(rebase_in_progress)" = true ] && [ "$(get_current_branch_name)" = "$MAIN_BRANCH_NAME" ]; then
    echo false
  else
    echo true
  fi
}


function steps {
  determine_branches_to_sync
  for branch_name in "${branches_to_sync[@]}"; do
    sync_branch_steps "$branch_name"
  done

  step "checkout $INITIAL_BRANCH_NAME"

  if [ "$HAS_REMOTE" = true ] && [ "$should_push_tags" = true ]; then
    step "push_tags"
  fi
}


run "$@"
