#!/usr/bin/env bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


# Echoes the names of all branches that should be synced in the current session
function branches_to_sync {
  ancestor_branches "$INITIAL_BRANCH_NAME" | tr ' ' '\n'
  echo "$INITIAL_BRANCH_NAME"
}


function preconditions {
  activate_driver_family 'code_hosting'
  if [ "$HAS_REMOTE" = true ]; then
    fetch
  fi
  ensure_knows_parent_branches "$INITIAL_BRANCH_NAME"
  export RUN_IN_GIT_ROOT=true
  export STASH_OPEN_CHANGES=true
}


function steps {
  for branch_name in $(branches_to_sync); do
    sync_branch_steps "$branch_name"
  done
  echo "push_branches $(branches_to_sync)"
  echo "create_pull_request $(remote_repository_name) $INITIAL_BRANCH_NAME $(parent_branch "$INITIAL_BRANCH_NAME")"
}


run "$@"
